### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Sagiri** [Sagiri/pluck#1]
- [ ] Implement Lum Berry effect
- [ ] Implement Oran Berry effect
- [ ] Implement updated Sitrus Berry Effect
- [ ] Implement Flavored HP Restore Berries
- [ ] Implement Stat Raising Berries
- [ ] Implement Starf Berry
- [ ] Confirm EV Reducing Berries don't need any special treatment.
- [ ] Confirm Damage Reducing Berries don't need any special treatment.
